server {
    listen 80;
    listen [::]:80;
    location /api {
        proxy_pass http://server:8000;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        add_header 'Access-Control-Allow-Origin' "$http_origin";
        add_header 'Access-Control-Allow-Credentials' 'true';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, DELETE';
        add_header 'Access-Control-Allow-Headers' 'Content-Type, x-access-token, Origin, X-Requested-With, Content-Type, Accept, Range';

   }
   location / {
        proxy_pass http://client:3000;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;

        add_header 'Access-Control-Allow-Origin' "$http_origin";
        add_header 'Access-Control-Allow-Credentials' 'true';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, DELETE';
        add_header 'Access-Control-Allow-Headers' 'Content-Type, x-access-token, Origin, X-Requested-With, Content-Type, Accept, Range';

        # set $cors '';

        # if ($http_origin ~* (localhost|www\.techmaster\.vn|techmaster\.vn)) {
        #     set $cors 'true';
        # }

        # if ($cors = 'true') {
        #     add_header 'Access-Control-Allow-Origin' "$http_origin";
        #     add_header 'Access-Control-Allow-Credentials' 'true';
        #     add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, DELETE';
        #     add_header 'Access-Control-Allow-Headers' 'Content-Type, x-access-token, Origin, X-Requested-With, Content-Type, Accept, Range';
        # }
    }
}